  - name: initiate env
    copy:
      src: semodule
      dest: /var/lib/
      owner: root
      group: root
      force: no

  - name: 
    shell: |
      /usr/bin/audit2allow -a -l -m csx-tests -o csx-tests/bucket/csx-tests-{{ ansible_date_time.epoch }}.te
      /usr/bin/python3 semerge-te.py -d csx-tests/bucket -o csx-tests/csx-tests.te
      /usr/bin/checkmodule -M -m -o csx-tests/csx-tests.mod csx-tests/csx-tests.te
      /usr/bin/semodule_package -o csx-tests/csx-tests.pp -m csx-tests/csx-tests.mod
      /usr/sbin/semodule -i csx-tests/csx-tests.pp
    args:
      chdir: /var/lib/semodule

  - name: copy back results
    copy:
      src: /var/lib/semodule/csx-tests/bucket
      dest: /tmp/
      force: no
      remote_src: yes
